version: '3'

services:
  db:
    image: mysql:5.7    
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: sample1234     
      MYSQL_DATABASE: sample
    ports:
      - 33308:3306
    volumes:
      - ./mysql:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']